### ISSUE TITLE
Readme.md中的步骤3

### ISSUE THREAD

**Issue by leasonyan** [BeatenMo/Pocket48RoomListen#1]
小透明不懂怎么编译，dalao有没有比较详细点的解释？另外，这个程序怎样才能被酷Q Air所识别？并没有找到cpk文件？

**Comment by SuxueCode** [comment]
vs 生成解决方案就是编译了
这个是基于酷Q的C# SDK开发的，所以最后插件并不是cpk文件
你生成完解决方案后，你就直接把文件夹内的Publish文件夹内所有东西拷贝至酷Q就好了
这个时候air应该会显示一个flexlive.cqeproxy的插件，这个就是C#的SDK
然后你所编译的插件，会在C# SDK的代理端显示（也就是Flexlive.CQP.CSharpProxy.exe）
